<?php
// $Id: shib_auth.module,v 1.3.4.5.2.31 2009/09/30 17:00:49 bajnokk Exp $
/**
 * @file
 * This is a Shibboleth authentication module.
 *
 * This module allow administrators to enable Shibboleth based authentication on their drupal installation.
 */

/**
 * Implements hook_menu().
 */
function shib_auth_advanced_menu() {
  $items = array();

      $items['admin/user/shib_auth/advanced'] = array(
    'title'            => t('Advanced settings'),
    'type'             => MENU_LOCAL_TASK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('shib_auth_admin_advanced'),
    'access arguments' => array('administer shibboleth authentication'),
    'weight'           => -6,
    'file' => 'shib_auth_advanced_forms.inc',
  );


  return $items;
} // function shib_auth_roles_menu()



/**
 * This function also gives roles to the user, if certain server fields were provided by the Shibboleth server
 */
function shib_auth_advanced_init() {
	if (shib_auth_session_valid())
		return true;
} // function shib_auth_roles_init()


