<?php
// $Id: shib_auth.module,v 1.3.4.5.2.31 2009/09/30 17:00:49 bajnokk Exp $
/**
 * @file
 * This is a Shibboleth authentication module.
 *
 * This module allow administrators to enable Shibboleth based authentication on their drupal installation.
 */
function shib_auth_advanced_get_config () {
  global $base_url;
  // Q: This method will disable using function-specific default value, need to check if we use it somewhere
  $config = array();
  $config['destroy_session'] = variable_get('shib_auth_auto_destroy_session', FALSE);
  $config['forceauthn'] = variable_get('shib_auth_forceauthn', FALSE);
  $config['ispassive'] = variable_get('shib_auth_is_passive', FALSE);
  $config['req_consent'] = variable_get('shib_auth_terms_accept', FALSE);
  $config['shib_auth_terms_url'] = variable_get('shib_auth_terms_url', '/');
  $config['terms_ver'] = variable_get('shib_auth_terms_ver', '');
  $config['logout_return'] = variable_get('shib_logout_url', $base_url);
 
  return $config;
}
/**
 * Implements hook_menu().
 */
function shib_auth_advanced_menu() {
  $items = array();

      $items['admin/user/shib_auth/advanced'] = array(
    'title'            => t('Advanced settings'),
    'type'             => MENU_LOCAL_TASK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('shib_auth_advanced_admin_advanced'),
    'access arguments' => array('administer shibboleth authentication'),
    'weight'           => -6,
    'file' => 'shib_auth_advanced_forms.inc',
  );

  return $items;
} // function shib_auth_roles_menu()
/**
 * This footer part executes isPassive script, if the option was checked on the configuration page
 */
function shib_auth_advanced_footer() {
  global $user;
  if (!shib_auth_session_valid() && $shib_auth_config['ispassive'] && !$user->uid) {
    $base = drupal_get_path('module', 'shib_auth');
    //TODO
    //A lot of parameterizing stuff, the script is pretty general now, the urls need to be generated based on handler/wayf/login/logout configs
    //Any1 good at that? ;)
    drupal_add_js($base.'/isPassive.js','module','footer');
  }
}


/**
 * This function also gives roles to the user, if certain server fields were provided by the Shibboleth server
 */
function shib_auth_advanced_init() {
	module_load_include('inc', 'shib_auth_advanced', 'forms');
	if (shib_auth_session_valid())
		return true;
} // function shib_auth_roles_init()


