<?php
// $Id: shib_auth.install,v 1.3.4.2.2.17 2009/10/20 11:25:33 dorion Exp $
/**
 * @file
 * This is the install file of the Shibboleth role assignment module for Drupal system
 *
 */
/**
 * Implementation of hook_install().
 *
 * Hook to install module
 */
function shib_auth_advanced_install() {
  
  drupal_set_message(t('Advanced Shibboleth authentication features installed successfully.'));
}
?>